### ISSUE TITLE
Using AraBERT preprocessor

### ISSUE THREAD

**Issue by MaramHasanain** [boushrabnd/CT19-T2_replication#1]
Boushra, for AraBERT v2, the model developers suggest using their own preprocessing function. 

https://github.com/boushrabnd/CT19-T2_replication/blob/b01431eacb8c52387341c0291f34a4359aa5bcc1/data_processing/preprocessor.py#L33

Please incorporate it from here: https://huggingface.co/aubmindlab/bert-base-arabertv2#preprocessing

**Comment by boushrabnd** [comment]
I changed the preprocessing function and ran the results.
